(()=>{
 const B=Body,fmt=(v,n=2)=>v==null?'—':v.toLocaleString('pt-BR',{maximumFractionDigits:n}),date=d=>format(d,{day:'2-digit',month:'2-digit',year:'numeric'}),colors=['#315e48','#b27c46','#627ba1','#956e94'];
 let bodyEditing=null,weightEditing=null,span='all',group='trunk';
 const groups={trunk:[['waist','Cintura'],['abdomen','Abdômen'],['hip','Quadril'],['chest','Peitoral']],arms:[['armL','Relaxado E'],['armR','Relaxado D'],['flexL','Contraído E'],['flexR','Contraído D']],legs:[['thighL','Coxa E'],['thighR','Coxa D'],['calfL','Panturrilha E'],['calfR','Panturrilha D']],other:[['shoulder','Ombro'],['neck','Pescoço'],['forearmL','Antebraço E'],['forearmR','Antebraço D']]};
 const records=()=>[...(state.body?.records||[])].sort((a,b)=>a.date.localeCompare(b.date));
 function chart(rows,series,unit,band=null,composition=false){
 const vals=rows.flatMap(r=>series.map(([k])=>B.value(r,k))).filter(v=>v!=null);if(!vals.length)return '<div class="body-empty">Nenhuma medida disponível neste período.</div>';
 let lo=Math.min(...vals,...(band||[])),hi=Math.max(...vals,...(band||[])),pad=Math.max((hi-lo)*.22,unit==='razão'?.04:unit==='kg'?2:2);lo=Math.max(0,lo-pad);hi+=pad;
 const left=46,right=486,top=17,bottom=174,w=right-left,h=bottom-top,minT=Date.parse(rows[0].date),maxT=Date.parse(rows.at(-1).date),x=r=>maxT===minT?(left+right)/2:left+(Date.parse(r.date)-minT)/(maxT-minT)*w,y=v=>bottom-(v-lo)/(hi-lo)*h;
 let svg=band?`<rect x="${left}" y="${y(band[1])}" width="${w}" height="${y(band[0])-y(band[1])}" fill="#eaf1e9"/>`:'';
 svg+=[0,.5,1].map(t=>{let v=lo+(hi-lo)*t;return `<line x1="${left}" x2="${right}" y1="${y(v)}" y2="${y(v)}" stroke="#e3e8df" stroke-dasharray="3 4"/><text x="${left-8}" y="${y(v)+4}" text-anchor="end">${fmt(v,unit==='razão'?2:1)}</text>`}).join('');
 series.forEach(([k,label],i)=>{let prev=null;rows.forEach(r=>{const v=B.value(r,k);if(v==null){prev=null;return}if(prev&&(!composition||prev.method===r.method))svg+=`<line x1="${x(prev)}" y1="${y(B.value(prev,k))}" x2="${x(r)}" y2="${y(v)}" stroke="${colors[i]}" stroke-width="2"/>`;svg+=`<circle cx="${x(r)}" cy="${y(v)}" r="4.5" fill="${colors[i]}" stroke="white" stroke-width="2"><title>${date(r.date)} · ${esc(label)}: ${fmt(v)} ${unit}</title></circle>`;prev=r})});
 svg+=`<text x="${maxT===minT?(left+right)/2:left}" y="204" text-anchor="${maxT===minT?'middle':'start'}">${date(rows[0].date)}</text>`;if(maxT!==minT)svg+=`<text x="${right}" y="204" text-anchor="end">${date(rows.at(-1).date)}</text>`;
 const desc=series.map(([k,label])=>{const valid=rows.filter(r=>B.value(r,k)!=null);return valid.length?`${label}: ${fmt(B.value(valid.at(-1),k))} ${unit} em ${date(valid.at(-1).date)}`:`${label}: não informado`}).join('; ');
 return `<svg class="body-chart" viewBox="0 0 510 216" role="img" aria-label="${esc(desc)}"><title>${esc(desc)}</title>${svg}</svg><div class="body-legend">${series.map(([k,l],i)=>`<span><i style="background:${colors[i]}"></i>${esc(l)} <b>${fmt(B.value(rows.at(-1),k))}</b></span>`).join('')}</div>`;
 }
 function weightSection(){
 const all=B.weightHistory(state.body),last=all.at(-1),first=all[0],delta=all.length>1?last.weight-first.weight:null;
 return `<section class="card weight-section"><div class="section-top"><div><p class="eyebrow">ENTRE UMA AVALIAÇÃO E OUTRA</p><h2>Acompanhar meu peso</h2></div><span class="muted">${all.length} ${all.length===1?'dia registrado':'dias registrados'}</span></div><p class="body-caption">Registre apenas a data e o peso. O peso das avaliações também aparece no gráfico, identificado no histórico.</p><form id="weightForm" class="weight-form"><label>Data<input id="weightDate" type="date" required></label><label>Peso (kg)<input id="weightValue" type="number" inputmode="decimal" min="0.01" max="500" step="0.01" required placeholder="Ex.: 69,5"></label><button class="primary" type="submit" id="saveWeight">Registrar peso</button><button class="quiet" type="button" id="cancelWeight" hidden>Cancelar edição</button></form><p id="weightError" role="alert"></p><div class="weight-summary"><span>Último peso <b>${last?fmt(last.weight)+' kg':'—'}</b>${last?' · '+date(last.date):''}</span><span>Variação desde o primeiro registro <b>${delta==null?'Aguardando nova pesagem':(delta>0?'+':'')+fmt(delta)+' kg'}</b></span></div>${chart(all,[['weight','Peso']],'kg')}<p class="body-caption">Compare registros feitos em condições semelhantes. A variação é exibida sem classificação automática de melhora ou piora. Havendo uma pesagem e uma avaliação na mesma data, o gráfico usa a pesagem; a avaliação permanece intacta.</p><details class="body-detail"><summary>Histórico de peso e correções</summary><div class="table-scroll"><table><thead><tr><th>Data</th><th>Peso</th><th>Origem</th><th></th></tr></thead><tbody>${[...all].reverse().map(r=>`<tr><td>${date(r.date)}</td><td>${fmt(r.weight)} kg</td><td>${r.origin}</td><td>${r.origin==='Pesagem'?`<button class="quiet" data-weight-edit="${r.date}">Editar peso</button><button class="quiet" data-weight-delete="${r.date}">Excluir peso</button>`:'Editar em avaliações'}</td></tr>`).join('')}</tbody></table></div></details></section>`;
 }
 function bindWeightForm(){
 const existing=(state.body?.weights||[]).find(r=>r.date===weightEditing);if(!existing)weightEditing=null;
 $('weightDate').max=H.key(new Date());$('weightDate').value=existing?.date||H.key(new Date());$('weightValue').value=existing?.weight??'';$('saveWeight').textContent=existing?'Salvar peso':'Registrar peso';$('cancelWeight').hidden=!existing;
 $('cancelWeight').onclick=()=>{weightEditing=null;renderBody()};
 $('weightForm').onsubmit=e=>{e.preventDefault();const d=$('weightDate').value,w=Number($('weightValue').value);if(!B.validDate(d)||d>H.key(new Date())||!Number.isFinite(w)||w<=0||w>500){$('weightError').textContent='Informe uma data até hoje e um peso maior que zero, até 500 kg.';return}if((state.body?.weights||[]).some(r=>r.date===d&&r.date!==weightEditing)){$('weightError').textContent='Já existe uma pesagem nesta data. Use Editar peso no histórico.';return}const old=weightEditing;weightEditing=null;if(update(s=>{s.body??={version:1,records:[]};s.body.weights=(s.body.weights||[]).filter(r=>r.date!==old);s.body.weights.push({date:d,weight:w})})){toast('Peso registrado. Seu gráfico foi atualizado.')}else weightEditing=old;};
 }
 document.addEventListener('click',e=>{const edit=e.target.closest('[data-weight-edit]'),del=e.target.closest('[data-weight-delete]');if(edit){weightEditing=edit.dataset.weightEdit;renderBody();$('weightValue').focus()}if(del&&confirm('Excluir esta pesagem? A avaliação corporal e os hábitos serão preservados.')){if(update(s=>{s.body.weights=s.body.weights.filter(r=>r.date!==del.dataset.weightDelete)})){weightEditing=null;renderBody();toast('Pesagem excluída.')}}});
 function panel(title,note,content){return `<section class="card body-card"><h2>${title}</h2><p class="body-caption">${note}</p>${content}</section>`}
 function stat(label,value,unit,detail){return `<div class="stat"><span class="label">${label}</span><strong>${value} <span>${unit}</span></strong><small>${detail}</small></div>`}
 function renderBody(){
 const all=records(),last=all.at(-1),rows=span==='all'?all:all.filter(r=>r.date>=H.shift(H.key(new Date()),-Number(span)+1));
 $('bodyPanel').innerHTML=`<section class="intro"><div><p class="eyebrow">CUIDADO QUE SE ACOMPANHA</p><h1>Seu corpo, ao longo do tempo.</h1><p class="muted">Saúde como referência. Constância como caminho.</p></div><button class="primary" id="addBody">+ Nova avaliação</button></section>
 ${weightSection()}<h2 class="assessment-heading">Avaliações completas</h2><div class="body-status"><span>${last?`Última avaliação: <b>${date(last.date)}</b> · ${all.length} ${all.length===1?'registro':'registros'}`:'Adicione sua primeira avaliação.'}</span><label>Gráficos <select id="bodyRange" aria-label="Período corporal"><option value="all">Todo o histórico</option><option value="90">Últimos 90 dias</option><option value="365">Último ano</option></select></label></div>
 <div class="stats body-stats">${last?stat('Peso',fmt(last.weight),'kg','Medida da última avaliação')+stat('Gordura corporal',fmt(last.fat),'%','Estimativa · '+esc(last.method||'método não informado'))+stat('IMC',fmt(B.value(last,'bmi')),'',B.bmiLabel(B.value(last,'bmi')))+stat('Cintura / altura',fmt(B.value(last,'whtr')),'',(B.value(last,'bmi')==null?'Interpretação requer IMC':B.value(last,'bmi')>=35?'Referência não aplicável com IMC ≥ 35':B.ratioLabel(B.value(last,'whtr')))):''}</div>
 <div class="body-insight">${all.length===1?'<b>Seu ponto de partida está registrado.</b> Uma avaliação descreve o momento; a próxima permitirá comparar as medidas.':'Compare medidas obtidas com o mesmo método e em condições semelhantes.'} <span>Variações não recebem automaticamente o rótulo de melhora ou piora.</span></div>
 <div class="body-grid">${panel('Peso e composição','kg · Massa magra inclui água, órgãos e ossos; não equivale a massa muscular.',chart(rows,[['weight','Peso'],['leanKg','Massa magra'],['fatKg','Massa gorda']],'kg',null,true))}${panel('Gordura corporal','% · Estimativa do método. Sem meta estética ou faixa universal de saúde.',chart(rows,[['fat','Gordura']],'%',null,true))}${panel('IMC ao longo do tempo','Faixa sombreada: 18,5 ≤ IMC < 25 · referência geral para adultos (CDC).',chart(rows,[['bmi','IMC']],'kg/m²',[18.5,25]))}${panel('Relação cintura / altura','Faixa sombreada: 0,40 a < 0,50 · referência NICE, aplicável com IMC < 35.',chart(rows,[['whtr','Cintura / altura']],'razão',[.4,.5]))}
 <section class="card body-card body-wide"><div class="section-top"><div><h2>Medidas corporais</h2><p class="body-caption">cm · Compare seu próprio histórico. Medidas maiores ou menores não definem saúde sozinhas.</p></div><select id="bodyGroup" aria-label="Grupo de medidas"><option value="trunk">Tronco</option><option value="arms">Braços</option><option value="legs">Pernas</option><option value="other">Ombros e antebraços</option></select></div>${chart(rows,groups[group],'cm')}</section></div>
 <section class="card body-history"><div class="section-top"><div><p class="eyebrow">SEU HISTÓRICO</p><h2>Avaliações e medidas</h2></div><span class="muted">${all.length} ${all.length===1?'avaliação':'avaliações'}</span></div><div class="table-scroll"><table><thead><tr><th>Data</th><th>Peso</th><th>Gordura</th><th>Cintura</th><th>IMC</th><th></th></tr></thead><tbody>${[...all].reverse().map(r=>`<tr><td>${date(r.date)}</td><td>${fmt(r.weight)} kg</td><td>${fmt(r.fat)} %</td><td>${fmt(r.waist)} cm</td><td>${fmt(B.value(r,'bmi'))}</td><td><button class="quiet" data-body-edit="${r.id}">Ver / editar</button></td></tr>`).join('')}</tbody></table></div>
 ${last?`<details class="body-detail"><summary>Ver todas as medidas da última avaliação</summary><dl class="measure-list">${B.fields.map(([k,l,u])=>`<div><dt>${l}</dt><dd>${fmt(last[k])}${last[k]!=null?' '+u:' · não informado'}</dd></div>`).join('')}<div><dt>Relação cintura / quadril</dt><dd>${fmt(B.value(last,'whr'))}</dd></div></dl><p class="body-caption">${esc(last.source||'Origem não informada')} · ${esc(last.method||'Método não informado')}</p><p class="body-caption">${esc(last.notes||'')}</p>${last.reported?`<p class="body-caption"><b>Conforme o relatório original:</b> ${esc(last.reported)}</p>`:''}</details>`:''}</section>
 <details class="card body-reference"><summary>Como interpretar · critérios e fontes de saúde</summary><p>IMC: peso (kg) ÷ altura² (m). Referência geral: abaixo de 18,5; de 18,5 a menos de 25; de 25 a menos de 30; 30 ou mais. É uma triagem; não distingue gordura de músculo nem resume sua saúde. Limiares individuais podem variar com o contexto clínico.</p><p>Cintura/altura: cintura (cm) ÷ altura (cm). Segundo o NICE, de 0,40 a menos de 0,50 corresponde à faixa de referência; 0,50 a menos de 0,60 indica adiposidade central aumentada, e ≥ 0,60, elevada. Use junto ao IMC quando ele for inferior a 35. Valores abaixo de 0,40 não são classificados aqui como “melhores”.</p><p>Meça a cintura no ponto médio entre a última costela e o topo do quadril, após expirar naturalmente. A técnica da avaliação enviada não foi confirmada: a comparação é indicativa. Cintura e abdômen são mantidos separadamente.</p><p>Percentual de gordura e perímetros servem ao acompanhamento. Estimativas por métodos diferentes não são diretamente intercambiáveis; linhas de composição são interrompidas quando o método muda. O peso “ideal” do relatório não foi adotado como meta.</p><p><b>Outra perspectiva:</b> estabilidade de peso pode acompanhar mudança de composição. Considere também disposição, força, sono e acompanhamento clínico. Estes gráficos não estabelecem diagnóstico.</p><p><a href="https://www.cdc.gov/bmi/adult-calculator/bmi-categories.html" target="_blank" rel="noopener">CDC · IMC em adultos</a> · <a href="https://www.nice.org.uk/guidance/ng246/chapter/Identifying-and-assessing-overweight-obesity-and-central-adiposity" target="_blank" rel="noopener">NICE · IMC e adiposidade central</a> · Consultados em 30/09/2026.</p></details>`;
 bindWeightForm();$('bodyRange').value=span;$('bodyGroup').value=group;$('bodyRange').onchange=e=>{span=e.target.value;renderBody()};$('bodyGroup').onchange=e=>{group=e.target.value;renderBody()};$('addBody').onclick=()=>openBody();
 }
 const dialog=document.createElement('dialog');dialog.id='bodyEditor';dialog.setAttribute('aria-labelledby','bodyEditorTitle');dialog.innerHTML=`<form id="bodyForm"><div class="section-top"><h2 id="bodyEditorTitle">Nova avaliação</h2><button type="button" id="closeBody" class="quiet" aria-label="Fechar avaliação">✕</button></div><p class="body-caption">Preencha somente o que mediu. Campos vazios ficam como não informados.</p><div class="body-form-grid"><label>Data da avaliação<input id="bodyDate" type="date" required></label><label>Método da composição<input id="bodyMethod" maxlength="200" placeholder="Ex.: Pollock 7, bioimpedância"></label></div><div class="body-form-grid">${B.fields.map(([k,l,u,max])=>`<label>${l} (${u})<input id="measure-${k}" type="number" inputmode="decimal" min="0.01" max="${max}" step="0.01"></label>`).join('')}</div><label>Origem / profissional<input id="bodySource" maxlength="300" placeholder="Ex.: avaliação na academia"></label><label>Observações<textarea id="bodyNotes" maxlength="3000" rows="3"></textarea></label><p class="body-caption">IMC e relações são calculados quando há as medidas necessárias. Com peso e gordura %, massas em kg podem ser estimadas se não informadas.</p><p id="bodyFormError" role="alert"></p><div class="form-actions"><button type="button" id="deleteBody" class="quiet">Excluir avaliação</button><button type="submit" class="primary">Salvar avaliação</button></div></form>`;document.body.append(dialog);
 function openBody(id){bodyEditing=id||null;const r=records().find(r=>r.id===id);$('bodyForm').reset();$('bodyEditorTitle').textContent=r?'Editar avaliação':'Nova avaliação';$('bodyDate').max=H.key(new Date());$('bodyDate').value=r?.date||H.key(new Date());B.fields.forEach(([k])=>$('measure-'+k).value=r?.[k]??(k==='height'?records().at(-1)?.height??'':''));$('bodyMethod').value=r?.method||'';$('bodySource').value=r?.source||'';$('bodyNotes').value=r?.notes||'';$('bodyFormError').textContent='';$('deleteBody').hidden=!r;dialog.showModal()}
 $('closeBody').onclick=()=>dialog.close();
 $('bodyForm').onsubmit=e=>{e.preventDefault();const d=$('bodyDate').value;if(!B.validDate(d)||d>H.key(new Date())){$('bodyFormError').textContent='Escolha uma data válida até hoje.';return}if(records().some(r=>r.date===d&&r.id!==bodyEditing)){$('bodyFormError').textContent='Já existe uma avaliação nesta data. Edite o registro existente.';return}
 const old=records().find(r=>r.id===bodyEditing),r={...old,id:bodyEditing||crypto.randomUUID(),date:d,method:$('bodyMethod').value.trim(),source:$('bodySource').value.trim(),notes:$('bodyNotes').value.trim()};B.fields.forEach(([k])=>r[k]=$('measure-'+k).value===''?null:Number($('measure-'+k).value));try{B.validate({version:1,records:[r]})}catch(err){$('bodyFormError').textContent=err.message;return}if(update(s=>{s.body??={version:1,records:[]};const i=s.body.records.findIndex(x=>x.id===r.id);if(i<0)s.body.records.push(r);else s.body.records[i]=r})){dialog.close();toast('Avaliação salva. Gráficos atualizados.')}};
 $('deleteBody').onclick=()=>{if(confirm('Excluir esta avaliação corporal? Os hábitos serão preservados.'))if(update(s=>{s.body.records=s.body.records.filter(r=>r.id!==bodyEditing)})){dialog.close();toast('Avaliação excluída.')}};
 document.addEventListener('click',e=>{const b=e.target.closest('[data-body-edit]');if(b)openBody(b.dataset.bodyEdit)});
 function showTab(body){$('habitsPanel').hidden=body;$('bodyPanel').hidden=!body;$('habitsTab').setAttribute('aria-pressed',String(!body));$('bodyTab').setAttribute('aria-pressed',String(body));history.replaceState(null,'',body?'#corpo':'#habitos');if(body)renderBody()}
 $('habitsTab').onclick=()=>showTab(false);$('bodyTab').onclick=()=>showTab(true);window.renderBody=renderBody;renderBody();showTab(location.hash==='#corpo');
})();
