(function(root){
 const fields=[['weight','Peso','kg',500],['height','Altura','cm',250],['fat','Gordura corporal','%',75],['fatKg','Massa gorda','kg',400],['leanKg','Massa magra','kg',400],['leanPct','Massa magra','%',100],['residualKg','Peso residual','kg',200],['waist','Cintura','cm',300],['abdomen','Abdômen','cm',300],['hip','Quadril','cm',300],['chest','Peitoral','cm',300],['shoulder','Ombro','cm',300],['neck','Pescoço','cm',100],['forearmL','Antebraço esquerdo','cm',100],['forearmR','Antebraço direito','cm',100],['armL','Braço relaxado esquerdo','cm',100],['armR','Braço relaxado direito','cm',100],['flexL','Braço contraído esquerdo','cm',100],['flexR','Braço contraído direito','cm',100],['thighL','Coxa esquerda','cm',150],['thighR','Coxa direita','cm',150],['calfL','Panturrilha esquerda','cm',100],['calfR','Panturrilha direita','cm',100]];
 const seed=()=>({version:1,records:[],weights:[]});
 const validDate=d=>typeof d==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(d)&&!isNaN(new Date(d+'T12:00:00'))&&new Date(d+'T12:00:00').toISOString().slice(0,10)===d;
 function validate(b){if(!b||b.version!==1||!Array.isArray(b.records)||b.records.length>2000)throw Error('Avaliações inválidas.');const ids=new Set(),dates=new Set();for(const r of b.records){if(!r||typeof r.id!=='string'||!/^[a-zA-Z0-9-]{1,80}$/.test(r.id)||ids.has(r.id)||!validDate(r.date)||dates.has(r.date))throw Error('Data ou identificação inválida.');ids.add(r.id);dates.add(r.date);for(const [k,,,max] of fields){if(r[k]!=null&&(typeof r[k]!=='number'||!Number.isFinite(r[k])||r[k]<=0||r[k]>max))throw Error('Medida inválida: '+k);}if(!fields.some(([k])=>k!=='height'&&r[k]!=null))throw Error('Informe ao menos uma medida.');for(const k of ['method','source','notes','reported'])if(r[k]!=null&&(typeof r[k]!=='string'||r[k].length>3000))throw Error('Texto inválido.');}if(b.weights!==undefined){if(!Array.isArray(b.weights)||b.weights.length>10000)throw Error('Pesagens inválidas.');const days=new Set();for(const w of b.weights){if(!w||!validDate(w.date)||days.has(w.date)||typeof w.weight!=='number'||!Number.isFinite(w.weight)||w.weight<=0||w.weight>500)throw Error('Pesagem inválida.');days.add(w.date);}}return b;}
 const value=(r,k)=>{if(k==='bmi')return r.weight&&r.height?r.weight/(r.height/100)**2:null;if(k==='whtr')return r.waist&&r.height?r.waist/r.height:null;if(k==='whr')return r.waist&&r.hip?r.waist/r.hip:null;if(k==='fatKg')return r.fatKg??(r.weight&&r.fat?r.weight*r.fat/100:null);if(k==='leanKg')return r.leanKg??(r.weight&&r.fat?r.weight*(1-r.fat/100):null);return r[k]??null};
 const bmiLabel=v=>v==null?'Sem dados':v<18.5?'Abaixo da faixa de referência':v<25?'Na faixa de referência':v<30?'Faixa de sobrepeso':'Faixa de obesidade';
 const ratioLabel=v=>v==null?'Sem dados':v<0.4?'Abaixo da faixa de referência':v<0.5?'Na faixa de referência':v<0.6?'Adiposidade central aumentada':'Adiposidade central elevada';
 const weightHistory=b=>{const days=new Map();for(const r of b?.records||[])if(r.weight!=null)days.set(r.date,{date:r.date,weight:r.weight,origin:'Avaliação'});for(const r of b?.weights||[])days.set(r.date,{...r,origin:'Pesagem'});return [...days.values()].sort((a,b)=>a.date.localeCompare(b.date));};
 root.Body={weightHistory,fields,seed,validate,value,bmiLabel,ratioLabel,validDate};if(typeof module!=='undefined')module.exports=root.Body;
})(typeof window!=='undefined'?window:globalThis);
