const test=require('node:test'),assert=require('node:assert/strict');
global.Persistence=require('./persistence-core.js');
const C=require('./sync-core.js'),Engine=require('./sync-engine.js');
const clone=Persistence.clone;
const base=()=>({version:1,habits:[{id:'h1',name:'Estudo',goal:'Ler',start:'2026-09-01',days:[0,1,2,3,4,5,6]}],checks:{h1:{}},body:{version:1,records:[],weights:[]},training:{version:1,sessions:[],exercises:[],workouts:[]},future:{settings:{custom:42},records:[{id:'future',value:1}]}});
function setup(start,cloud,owner='user-a',persisted){let state=clone(start),store=new Map(persisted||[]),messages=[];const storage={getItem:k=>store.get(k)??null,setItem:(k,v)=>store.set(k,v)};const config={store:storage,data:{read:()=>clone(state),blocked:()=>false,protect:(k,v)=>storage.setItem(k,JSON.stringify(v)),apply:(next,expected)=>{if(!C.equal(state,expected))return false;state=clone(next);return true;}},status:s=>messages.push(s),readCloud:async user=>{assert.equal(user,owner);return clone(cloud);},saveCloud:async(user,revision,next)=>{assert.equal(user,owner);if(revision!==cloud.revision)return {...clone(cloud),saved:false};cloud.state=clone(next);cloud.revision++;return {...clone(cloud),saved:true};}};const engine=new Engine(config);return {engine,config,store,messages,read:()=>clone(state),edit:fn=>fn(state),reload:()=>setup(state,cloud,owner,store.entries())};}
test('unrelated changes merge and deliberate removals stay removed',()=>{let b=base(),l=clone(b),r=clone(b);b.checks.h1['2026-09-10']=true;l=clone(b);r=clone(b);delete l.checks.h1['2026-09-10'];r.checks.h1['2026-09-11']=true;l.body.weights.push({date:'2026-09-10',weight:80,custom:'keep'});r.future.settings.newField='remote';const out=C.reconcile(b,l,r);assert.equal(out.conflicts.length,0);assert(!out.state.checks.h1['2026-09-10']);assert(out.state.checks.h1['2026-09-11']);assert.equal(out.state.body.weights[0].custom,'keep');assert.equal(out.state.future.settings.custom,42);assert.equal(out.state.future.settings.newField,'remote');});
test('same workout stays atomic and offers both resolutions',()=>{const b=base();b.training.sessions.push({id:'s1',name:'Pernas',exercises:[{sets:[{weight:20,reps:10}]}]});const l=clone(b),r=clone(b);l.training.sessions[0].exercises[0].sets[0].weight=30;r.training.sessions[0].exercises[0].sets[0].reps=8;const out=C.reconcile(b,l,r);assert.deepEqual(out.conflicts,['training.sessions:s1']);assert.deepEqual(out.state.training.sessions,l.training.sessions);assert.deepEqual(C.reconcile(b,l,r,'remote').state.training.sessions,r.training.sessions);});
test('future field deletion and null remain distinct from missing',()=>{const b=base(),l=clone(b),r=clone(b);delete l.future.settings.custom;r.future.other=null;const out=C.reconcile(b,l,r);assert(!Object.hasOwn(out.state.future.settings,'custom'));assert.equal(out.state.future.other,null);});
test('two devices, stale revision retry, offline reload and check removal',async()=>{const cloud={state:base(),revision:1};const a=setup(base(),cloud),b=setup(base(),cloud);for(const d of [a,b]){d.engine.link('user-a',true);await d.engine.flush('user-a');}a.edit(s=>s.checks.h1['2026-09-10']=true);b.edit(s=>s.body.weights.push({date:'2026-09-10',weight:80}));await Promise.all([a.engine.flush('user-a'),b.engine.flush('user-a')]);await a.engine.flush('user-a');assert.deepEqual(a.read(),b.read());assert(cloud.state.checks.h1['2026-09-10']);assert.equal(cloud.state.body.weights.length,1);b.edit(s=>delete s.checks.h1['2026-09-10']);const offline=setup(b.read(),cloud,'user-a',b.store.entries());offline.engine.readCloud=async()=>{throw Error('offline');};assert.equal(await offline.engine.flush('user-a'),false);assert(!offline.read().checks.h1['2026-09-10']);const again=offline.reload();await again.engine.flush('user-a');await a.engine.flush('user-a');assert(!cloud.state.checks.h1['2026-09-10']);assert.deepEqual(a.read(),cloud.state);assert.equal(cloud.state.future.settings.custom,42);});
test('initial linking gathers histories without replacing missing areas',async()=>{const current=base();current.body.weights.push({date:'2026-09-10',weight:80});const cloud={state:base(),revision:1};cloud.state.checks.h1['2026-09-09']=true;const a=setup(current,cloud);a.engine.link('user-a',false);await a.engine.flush('user-a');assert(cloud.state.checks.h1['2026-09-09']);assert.equal(cloud.state.body.weights.length,1);assert.equal(JSON.parse(a.store.get('constancia.recovery.before-account-link')).body.weights.length,1);});
test('conflict blocks upload and protects both versions until chosen',async()=>{const current=base();current.body.weights=[{date:'2026-09-10',weight:80}];const cloud={state:clone(current),revision:1};const a=setup(current,cloud);a.engine.link('user-a',true);await a.engine.flush('user-a');a.edit(s=>s.body.weights[0].weight=81);cloud.state.body.weights[0].weight=82;cloud.revision++;assert.equal(await a.engine.flush('user-a'),false);assert.equal(cloud.state.body.weights[0].weight,82);const recovery=JSON.parse(a.store.get('constancia.recovery.sync-conflicts'));assert.equal(recovery.local.body.weights[0].weight,81);assert.equal(recovery.remote.body.weights[0].weight,82);await a.engine.flush('user-a','remote');assert.equal(a.read().body.weights[0].weight,82);});
test('edits during upload survive and reach the cloud on the next pass',async()=>{const cloud={state:base(),revision:1},a=setup(base(),cloud);a.engine.link('user-a',true);await a.engine.flush('user-a');a.edit(s=>s.checks.h1['2026-09-10']=true);const save=a.engine.saveCloud;let once=true;a.engine.saveCloud=async(...args)=>{if(once){once=false;a.edit(s=>s.checks.h1['2026-09-11']=true);}return save(...args);};await a.engine.flush('user-a');assert(cloud.state.checks.h1['2026-09-10']);assert(cloud.state.checks.h1['2026-09-11']);});
test('account switching and cancellation cannot upload the previous history',async()=>{const cloud={state:base(),revision:1},a=setup(base(),cloud);a.engine.link('user-a',true);assert.throws(()=>a.engine.link('user-b',false));assert.equal(await a.engine.flush('user-b'),false);const previous=clone(cloud);a.engine.readCloud=async()=>{a.engine.cancel();return clone(cloud);};assert.equal(await a.engine.flush('user-a'),false);assert.deepEqual(cloud,previous);});
test('quota or invalid metadata blocks linking without changing history',()=>{const cloud={state:base(),revision:1},a=setup(base(),cloud);a.config.data.protect=()=>{throw Error('quota');};assert.throws(()=>a.engine.link('user-a',false));assert.equal(a.engine.meta.owner,undefined);assert.deepEqual(a.read(),base());a.store.set('constancia.sync.v1','{"version":999}');assert.throws(()=>new Engine(a.config));});
test('pristine phone receives cloud history without uploading starter habits',async()=>{const local=base(),cloud={state:base(),revision:3};cloud.state.habits=[{...local.habits[0],name:'Personalizado',id:'custom'}];cloud.state.checks={custom:{'2026-09-10':true}};const a=setup(local,cloud);a.engine.link('user-a',true);await a.engine.flush('user-a');assert.equal(cloud.revision,3);assert.deepEqual(a.read(),cloud.state);});
