(function(){
 'use strict';
 const $=id=>document.getElementById(id),data=window.ConstanciaData;
 const client=ConstanciaCloud.createClient('https://ahsnobrlcyaefdanjdsm.supabase.co','sb_publishable__bIEZl3QmcWLLeMzJBSjyw_xIYX_YQm',{auth:{storageKey:'constancia.auth.v1',persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
 let session=null,timer,engine,authBusy=false;
 const message=(s)=>{$('authMessage').textContent=s;};
 function status(text,kind,error){$('syncStatus').textContent=text;$('syncStatus').dataset.kind=kind||'';$('storageFooter').textContent=text;if(error){const code=error.code;if(code==='PGRST301'||error.status===401)message('Seu acesso expirou. Entre novamente para sincronizar.');else message('Os registros continuam neste aparelho. Confira a conexão e tente novamente.');}}
 const err=e=>{const codes={invalid_credentials:'E-mail ou senha incorretos.',email_not_confirmed:'Confirme o e-mail recebido antes de entrar.',email_address_not_authorized:'Use o e-mail da sua conta Supabase. O envio para outros endereços ainda precisa ser configurado.',over_email_send_rate_limit:'Aguarde antes de pedir outro e-mail de confirmação.',user_already_exists:'Esta conta já existe. Use Entrar.',weak_password:'Escolha uma senha mais forte, com pelo menos 8 caracteres.',otp_expired:'O código expirou. Solicite uma nova confirmação.'};return codes[e.code]||'Não foi possível concluir o acesso. Confira os dados e tente novamente.';};
 function account(){const user=session?.user;$('authArea').hidden=!!user;$('connectedArea').hidden=!user;$('accountOpen').querySelector('span').textContent=user?'Minha conta':'Conectar';$('accountEmail').textContent=user?'Conectado como '+user.email:'';const mismatch=!!user&&!!engine?.meta.owner&&engine.meta.owner!==user.id;$('accountMismatch').hidden=!mismatch;$('linkArea').hidden=!user||!!engine?.meta.owner;$('linkedArea').hidden=!user||!engine?.owned(user.id);$('linkText').textContent=data.pristine()?'Vincule este aparelho para receber seu histórico da nuvem.':'Este aparelho já tem registros. Ao vincular, eles serão reunidos com o histórico privado da sua conta.';if(mismatch)status('Histórico de outra conta · Entre na conta original');else if(!user)status(engine?.meta.owner?'Salvo neste aparelho · Entre para sincronizar':'Salvo neste aparelho · Conecte sua conta');else if(!engine?.meta.owner)status('Conta conectada · Vincule seu histórico');}
 async function flush(preference){if(!session){account();return;}if(navigator.onLine===false){status('Salvo neste aparelho · Aguardando internet');return;}await engine.flush(session.user.id,preference);account();if(engine.conflict){$('conflictSummary').textContent=engine.conflict.conflicts.length+' registro(s) com diferenças.';if(!$('conflictDialog').open)$('conflictDialog').showModal();}}
 function schedule(delay=900){clearTimeout(timer);timer=setTimeout(()=>flush(),delay);}
 try{engine=new ConstanciaSyncEngine({store:localStorage,data,status,readCloud:async user=>{const {data:row,error}=await client.from('constancia_states').select('state,revision,updated_at').eq('user_id',user).maybeSingle();if(error)throw error;if(row)Habits.validate(row.state);return row||{state:null,revision:0};},saveCloud:async(user,revision,state)=>{Habits.validate(state);const {data:row,error}=await client.rpc('constancia_save',{owner_id:user,expected_revision:revision,next_state:state});if(error)throw error;Habits.validate(row.state);return row;}});}catch{status('Seu histórico está salvo · Sincronização precisa de revisão');message('Não foi possível ler a configuração da sincronização. Faça um backup antes de continuar.');return;}
 engine.onComplete=()=>{if(session&&engine.owned(session.user.id)&&!engine.conflict&&!ConstanciaSyncCore.equal(data.read(),engine.meta.base)&&navigator.onLine)schedule(15000);};
 $('accountOpen').onclick=()=>{account();$('accountDialog').showModal();};$('accountClose').onclick=()=>$('accountDialog').close();$('syncStatusButton').onclick=()=>{if(engine.conflict)$('conflictDialog').showModal();else $('accountOpen').click();};
 async function authenticate(mode){if(authBusy)return;const email=$('authEmail').value.trim(),password=$('authPassword').value;if(!$('authForm').reportValidity())return;authBusy=true;$('authSignin').disabled=$('authSignup').disabled=true;message(mode==='signup'?'Criando sua conta…':'Entrando…');try{const response=mode==='signup'?await client.auth.signUp({email,password,options:{emailRedirectTo:'https://petersfilms.github.io/constancia/'}}):await client.auth.signInWithPassword({email,password});if(response.error)throw response.error;$('authPassword').value='';session=response.data.session;if(!session){$('authVerify').hidden=false;message('Confirme o e-mail recebido e volte ao aplicativo para entrar. Se receber um código, você também pode inseri-lo abaixo.');}else{message('Você entrou. Vincule o histórico deste aparelho para começar.');account();schedule(0);}}catch(e){message(err(e));}finally{authBusy=false;$('authSignin').disabled=$('authSignup').disabled=false;}}
 $('authForm').onsubmit=e=>{e.preventDefault();authenticate('signin');};$('authSignup').onclick=()=>authenticate('signup');
 $('authVerifyButton').onclick=async()=>{const {error}=await client.auth.verifyOtp({email:$('authEmail').value.trim(),token:$('authCode').value.trim(),type:'signup'});message(error?err(error):'E-mail confirmado. Entre na sua conta.');};
 $('authForgot').onclick=async()=>{if(!$('authEmail').reportValidity())return;const {error}=await client.auth.resetPasswordForEmail($('authEmail').value.trim(),{redirectTo:'https://petersfilms.github.io/constancia/'});message(error?err(error):'Se a conta existir, você receberá um link para criar outra senha.');};
 $('resetForm').onsubmit=async e=>{e.preventDefault();const {error}=await client.auth.updateUser({password:$('resetPassword').value});if(error){message(err(error));return;}$('resetPassword').value='';$('resetArea').hidden=true;message('Senha atualizada.');};
 $('linkHistory').onclick=()=>{try{engine.link(session.user.id,data.pristine());account();flush();}catch(e){message(e.message);}};
 $('syncNow').onclick=()=>flush();$('authSignout').onclick=async()=>{engine.cancel();await client.auth.signOut({scope:'local'});session=null;account();message('Você saiu. Os registros deste aparelho foram preservados.');};
 $('cloudBackup').onclick=async()=>{try{const cloud=await engine.readCloud(session.user.id);if(!cloud.state){message('Ainda não há um histórico na nuvem.');return;}downloadBackup(JSON.stringify(cloud.state,null,2),'constancia-nuvem-'+Habits.key(new Date())+'.json');}catch{message('Não foi possível baixar a cópia. Os dados locais continuam disponíveis em Backup.');}};
 $('cloudRecovery').onclick=async()=>{const {data:rows,error}=await client.from('constancia_snapshots').select('state,day').eq('user_id',session.user.id).order('day',{ascending:false}).limit(1);if(error||!rows?.length){message('Não há uma cópia diária disponível ainda. Ela é criada quando um histórico sincronizado é atualizado.');return;}downloadBackup(JSON.stringify(rows[0].state,null,2),'constancia-recuperacao-'+rows[0].day+'.json');};
 $('conflictLocal').onclick=()=>{$('conflictDialog').close();flush('local');};$('conflictRemote').onclick=()=>{$('conflictDialog').close();flush('remote');};$('conflictClose').onclick=()=>$('conflictDialog').close();$('conflictBackup').onclick=()=>downloadBackup(localStorage.getItem('constancia.recovery.sync-conflicts')||'{}','constancia-versoes-em-conflito.json');
 client.auth.onAuthStateChange((event,next)=>{if(session?.user.id!==next?.user.id)engine.cancel();session=next;account();if(event==='PASSWORD_RECOVERY'){$('resetArea').hidden=false;$('accountDialog').showModal();}schedule(0);});
 window.addEventListener('constancia:change',()=>{status(session?'Salvo neste aparelho · Sincronização pendente':'Salvo neste aparelho');schedule();});window.addEventListener('online',()=>schedule(0));window.addEventListener('offline',()=>status('Salvo neste aparelho · Aguardando internet'));window.addEventListener('focus',()=>schedule(0));document.addEventListener('visibilitychange',()=>{if(!document.hidden)schedule(0);});
 window.addEventListener('storage',e=>{if(e.key===engine.key){try{engine.meta=engine.load();account();schedule();}catch{status('Configuração alterada · Reabra o aplicativo');}}else if(e.key==='constancia.v1')schedule();});setInterval(()=>{if(!document.hidden&&session)schedule(0);},30000);account();
})();
