const fs=require('node:fs'),assert=require('node:assert/strict');
const {JSDOM,VirtualConsole}=require('jsdom');
const clone=x=>JSON.parse(JSON.stringify(x));
const sample={version:1,habits:[{id:'habit-0',name:'Estudo / leitura',goal:'Ler',start:'2026-09-01',days:[0,1,2,3,4,5,6]}],checks:{'habit-0':{'2026-09-30':true}},body:{version:1,records:[{id:'body-test',date:'2026-09-25',weight:70,height:170,notes:'original',custom:'body field'}],weights:[{date:'2026-09-29',weight:71}],future:'body future'},training:{version:1,sessions:[{id:'session-1',date:'2026-09-24',name:'Peito e tríceps',performance:4,energy:4,food:3,stress:2,sleep:8,extra:'session extra',exercises:[{id:'exercise-1',name:'Supino reto',method:'Progressão',notes:'nota',custom:'exercise extra',sets:[{reps:10,weight:40,rir:2,notes:'set note',custom:'set extra'}]}]},{id:'session-2',date:'2026-09-30',name:'Peito e tríceps',performance:3,energy:3,food:4,stress:3,sleep:7,exercises:[{id:'exercise-2',name:'Supino reto',method:'Progressão',notes:'',sets:[{reps:8,weight:45,rir:2,notes:''}]}]}],future:'training future'},futureTab:{version:7,records:[{id:'untouched',measure:42}]}};
function boot(data){const errors=[],vc=new VirtualConsole();vc.on('jsdomError',e=>errors.push(e));const dom=new JSDOM(fs.readFileSync('index.html','utf8'),{url:'https://constancia-test.invalid/#treinos',runScripts:'outside-only',virtualConsole:vc});const w=dom.window;w.localStorage.setItem('constancia.v1',(typeof data==='string'?data:JSON.stringify(data)));w.HTMLDialogElement.prototype.showModal=function(){this.open=true;};w.HTMLDialogElement.prototype.close=function(){this.open=false;};w.Element.prototype.scrollIntoView=function(){};w.confirm=()=>true;w.URL.createObjectURL=()=> 'blob:test';w.URL.revokeObjectURL=()=>{};for(const f of ['persistence-core.js','body-core.js','training-core.js','core.js','sync-core.js','app.js','body.js','training.js'])require('node:vm').runInContext(fs.readFileSync(f,'utf8'),dom.getInternalVMContext(),{filename:f});const $=id=>w.document.getElementById(id);return {w,$,errors,dom,read:()=>JSON.parse(w.localStorage.getItem('constancia.v1')),click:el=>el.click(),change:(el,value)=>{el.value=value;el.dispatchEvent(new w.Event('change',{bubbles:true}));},submit:()=> $('trainingForm').dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}))};}
(async()=>{
const a=boot(sample),{$,w}=a;assert.deepEqual(a.read(),sample);assert.deepEqual(JSON.parse(w.localStorage.getItem('constancia.recovery.before-mobile-sync-v4')),sample);assert.equal($('trainingPanel').hidden,false);assert.equal($('habitsPanel').hidden,true);
let card=$('trainingPanel').querySelector('[data-workout]');assert.equal($('trainingPanel').querySelectorAll('[data-workout]').length,1);a.click(card);assert.match($('trainingPanel').textContent,/Sessões registradas2/);assert.equal($('trainingPanel').querySelectorAll('.load-chart').length,1);assert.match($('trainingPanel').textContent,/45 kg/);
a.change($('rankMode'),'exercise');a.change($('rankExercise'),'Supino reto');assert.equal($('trainingPanel').querySelectorAll('.training-ranking tbody tr').length,2);
a.click($('trainingPanel').querySelector('[data-training-edit="session-1"]'));
assert.equal($('trainingName').value,'Peito e tríceps');assert.equal($('trainingEnergy').selectedOptions[0].textContent,'Boa');assert.equal($('trainingStress').selectedOptions[0].textContent,'Baixo');
const box=$('exerciseBuilder').children[0];a.change(box.querySelector('[data-exercise=group]'),'Peito');a.submit();
let after=a.read();assert.equal(after.training.sessions[0].extra,'session extra');assert.equal(after.training.sessions[0].exercises[0].custom,'exercise extra');assert.equal(after.training.sessions[0].exercises[0].sets[0].custom,'set extra');assert.equal(after.training.sessions[0].exercises[0].sets[0].notes,'set note');assert.equal(after.training.sessions[0].exercises[0].sets[0].weight,40);assert.deepEqual(after.body,sample.body);assert.deepEqual(after.habits,sample.habits);assert.deepEqual(after.checks,sample.checks);assert.deepEqual(after.futureTab,sample.futureTab);assert.equal(after.training.future,'training future');
a.click($('addTraining'));a.change($('trainingName'),'__new__');$('newWorkoutName').value='Treino A';a.change($('trainingEnergy'),'5');a.change($('trainingFood'),'4');a.change($('trainingStress'),'1');let b=$('exerciseBuilder').children[0];a.change(b.querySelector('[data-exercise=name]'),'Supino reto');assert.equal(b.querySelector('[data-exercise=group]').value,'Peito');a.change(b.querySelector('[data-set=type]'),'bar');b.querySelector('[data-set=weight]').value='20';b.querySelector('[data-set=weight]').dispatchEvent(new w.Event('input',{bubbles:true}));assert.match(b.querySelector('.load-total').textContent,/Total: 30 kg/);b.querySelector('[data-set=reps]').value='12';b.querySelector('[data-set=rir]').value='3';a.click($('addExercise'));b=$('exerciseBuilder').children[1];a.change(b.querySelector('[data-exercise=name]'),'__new__');b.querySelector('[data-exercise=newName]').value='Flexão';a.change(b.querySelector('[data-exercise=group]'),'Peito');a.change(b.querySelector('[data-set=type]'),'body');b.querySelector('[data-set=reps]').value='15';a.submit();
after=a.read();assert.equal(after.training.sessions.length,3);const added=after.training.sessions.at(-1);assert.equal(w.Training.volume(added),360);assert.equal(w.Training.load(added.exercises[0].sets[0]),30);assert.equal(added.exercises[1].sets[0].weight,0);assert.equal(added.energy,5);assert.equal(added.stress,1);assert.equal($('trainingPanel').querySelectorAll('[data-workout]').length,2);assert.deepEqual(after.futureTab,sample.futureTab);
const again=boot(after);assert.deepEqual(again.read(),after);again.click(again.$('addTraining'));assert([...again.$('trainingName').options].some(o=>o.text==='Treino A'));const options=again.$('exerciseBuilder').querySelector('[data-exercise=name]').options;assert([...options].some(o=>o.text==='Flexão'));
a.change($('rankMode'),'group');a.change($('rankGroup'),'Peito');assert.match($('trainingPanel').querySelector('.training-ranking').textContent,/Supino reto/);
await $('import').onchange({target:{files:[{size:500,text:async()=>JSON.stringify({version:1,habits:sample.habits,checks:sample.checks})}],value:'file'}});$('confirmRestore').onclick();assert.deepEqual(a.read().training,after.training);assert.deepEqual(a.read().futureTab,sample.futureTab);assert.deepEqual(a.read().body,sample.body);assert.deepEqual(JSON.parse(w.localStorage.getItem('constancia.recovery.before-restore')),after);
const union=boot(sample),imported=clone(sample);imported.habits.push({id:'habit-new',name:'Alimentação',goal:'Meta',start:'2026-09-01',days:[0,1,2,3,4,5,6]});imported.checks['habit-0']['2026-09-29']=true;imported.training.sessions.push({...clone(sample.training.sessions[0]),id:'session-new',date:'2026-09-28'});imported.body.weights.push({date:'2026-09-30',weight:72});imported.futureTab.records.push({id:'future-new',measure:43});
const upload={target:{files:[{size:900,text:async()=>JSON.stringify(imported)}],value:'file'}};await union.$('import').onchange(upload);assert.equal(union.$('importMode').value,'merge');assert.match(union.$('importSummary').textContent,/3 sessões de treino/);union.$('confirmRestore').onclick();const combined=union.read();assert.equal(combined.habits.length,2);assert.equal(combined.training.sessions.length,3);assert.equal(combined.body.weights.length,2);assert.equal(combined.futureTab.records.length,2);assert.deepEqual(JSON.parse(union.w.localStorage.getItem('constancia.recovery.before-restore')),sample);assert.deepEqual(JSON.parse(union.w.localStorage.getItem('constancia.recovery.import-source')),imported);await union.$('import').onchange(upload);union.$('confirmRestore').onclick();assert.deepEqual(union.read(),combined);const unionReload=boot(combined);assert.deepEqual(unionReload.read(),combined);unionReload.dom.window.close();union.dom.window.close();
const backup=a.read();a.click($('addTraining'));w.localStorage.setItem('constancia.v1',JSON.stringify({...backup,futureTab:{newer:true}}));const c=$('exerciseBuilder').children[0];a.change($('trainingName'),'Peito e tríceps');a.change(c.querySelector('[data-exercise=name]'),'Supino reto');c.querySelector('[data-set=reps]').value='10';c.querySelector('[data-set=weight]').value='100';a.submit();assert.equal(a.read().training.sessions.length,3);assert.equal(a.read().futureTab.newer,true);assert.match($('toast').textContent,/Outra aba/);
const broken=boot('{invalid-original');assert.equal(broken.w.localStorage.getItem('constancia.v1'),'{invalid-original');assert.equal(broken.w.localStorage.getItem('constancia.recovery.before-mobile-sync-v4'),'{invalid-original');assert.equal(broken.$('dataStatus').hidden,false);broken.w.document.getElementById('addTraining').click();assert.equal(broken.w.localStorage.getItem('constancia.v1'),'{invalid-original');broken.dom.window.close();
assert.equal(a.errors.length,0);assert.equal(again.errors.length,0);a.dom.window.close();again.dom.window.close();
console.log('OK: DOM completo: filtros, gráfico de exercício, edição sem perda, catálogos reutilizáveis, barra/corporal, backup antigo, recarga e conflito entre abas.');
})().catch(e=>{console.error(e);process.exitCode=1;});
